---

- name: upgrade system
  apt: upgrade=dist update_cache=yes

- name: install NGINX
  apt: name=nginx state=latest

- name: create NGINX directory
  file: name=/etc/nginx/sites-enabled state=directory

- name: install letsencrypt
  apt: name=letsencrypt state=latest

- name: create letsencrypt directory
  file: name=/var/www/letsencrypt state=directory

- name: remove default NGINX config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: copy nginx common files
  copy:
    src: templates/nginx/
    dest: /etc/nginx
  notify:
    - restart nginx

- name: install tmp NGINX config for authenticating domain with letsencrypt
  template:
    src: templates/tmp-nginx.j2
    dest: /etc/nginx/sites-enabled/{{ domain_name }}
  notify:
    - restart nginx

- name: create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m "{{ letsencrypt_email }}" --agree-tos -d "{{ domain_name }}"
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}

- name: generate dhparams
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: setup final NGINX config template
  template:
    src: templates/{% if template is not defined %}nginx.j2{% else %}{{ template }}{% endif %}
    dest: /etc/nginx/sites-enabled/{{ domain_name }}

- name: run handlers
  meta: flush_handlers

- name: add letsencrypt cronjob
  cron:
    name: "{{ domain_name }}_renewal"
    special_time: weekly
    job: letsencrypt --renew-by-default certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} && service nginx reload