---

- name: uninstall NGINX
  apt: name=nginx state=absent

- name: delete NGINX directory
  file: >
    path=/etc/nginx/
    state=absent

- name: uninstall letsencrypt
  apt: name=letsencrypt state=absent

- name: delete letsencrypt directory
  file: >
    path=/var/www/letsencrypt
    state=absent